### ISSUE TITLE
mplot2d issue

### ISSUE THREAD

**Issue by jmlarson1** [jmlarson1/QFI-Opt#49]
I'm trying to run the `calculate_qfi.py` example on the `main` branch and I observe the following error:

```
[jlarson@x1carbon QFI-Opt] git checkout main 
Already on 'main'
Your branch is up to date with 'origin/main'.

[jlarson@x1carbon QFI-Opt] git pull
Already up to date.

[jlarson@x1carbon QFI-Opt] cd qfi_opt/examples/

[jlarson@x1carbon examples] python calculate_qfi.py 
Traceback (most recent call last):
  File "/home/jlarson/active/QFI-Opt/qfi_opt/examples/calculate_qfi.py", line 4, in <module>
    from qfi_opt import spin_models
  File "/home/jlarson/active/QFI-Opt/qfi_opt/__init__.py", line 1, in <module>
    from . import dissipation, examples, plot, spin_models
  File "/home/jlarson/active/QFI-Opt/qfi_opt/plot.py", line 92, in <module>
    ) -> tuple[mpl.figure.Figure, list[mplot3d.axes3d.Axes3D]]:
NameError: name 'mplot3d' is not defined
```

Is this new? (I wouldn't expect to need `mplot3d` to run this file.)

**Comment by perlinm** [comment]
@sriharikrishna we have a new error when running `pythong qfi_opt/examples/calculate_qfi.py`:
```
RuntimeError: Cannot reverse-mode autodifferentiate when using `diffeqsolve(..., max_steps=None, adjoint=RecursiveCheckpointAdjoint(checkpoints=None))`. This is because JAX needs to know how much memory to allocate for saving the forward pass. You should either put a bound on the maximum number of steps, or explicitly specify how many checkpoints to use.
```
Any guidance on how to fix this?
